In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
import os

In [2]:
path = "Data/train"
os.listdir(path)
df = pd.DataFrame()
for file in os.listdir(path):
    if file.endswith('.csv'):
        df1 = pd.read_csv(path + "/"+ file)
        df = pd.concat([df,df1])

df

,ID,Tune Date,System,Test ID,69 m/z,70 m/z,219 m/z,220 m/z,502 m/z,503 m/z,...,Emission,EM Volts,Ent Lens,Ion Focus,Repeller,Ent Lens offset,Filament,Width219,Temp,Condition
0,1,Wed Dec 22 11:13:45 2021,19,2,389888,4815,352320,15620,24096,2770,...,35.0,1718,7.00,78.8,21.41,18.570,1,-0.004,230,0
1,2,Fri Dec 24 09:37:12 2021,19,2,322880,3532,359616,15261,27592,2709,...,35.0,1812,12.00,75.9,20.57,17.320,1,-0.010,230,0
2,3,Mon Jan 10 14:24:06 2022,19,2,316608,3490,379840,16608,29992,3163,...,35.0,1718,12.00,74.0,18.40,16.310,1,-0.011,230,0
3,4,Fri Jan 14 15:39:12 2022,19,2,296128,3154,368064,15829,28832,2954,...,35.0,1765,12.00,72.1,18.06,16.310,1,-0.014,230,0
4,5,Tue Jan 18 07:21:40 2022,19,2,300544,2958,375296,16720,29136,2995,...,35.0,1812,12.00,72.1,17.39,16.310,1,-0.012,230,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,69,Fri Feb 12 10:57:01 2021,36,1,335808,3349,290176,13034,29240,2957,...,34.6,1568,20.18,90.3,26.93,14.273,2,-0.015,250,0
69,70,Mon Feb 15 11:32:31 2021,36,1,363776,4016,314688,13293,29592,3278,...,34.6,1568,20.18,90.3,26.13,14.273,2,-0.017,250,0
70,71,Tue Feb 16 10:21:43 2021,36,1,353280,4184,311808,12936,31808,3364,...,34.6,1568,22.67,90.3,26.93,13.071,2,-0.018,250,0
71,72,Wed Feb 17 13:38:17 2021,36,1,492288,5296,423104,18760,44760,4126,...,34.6,1615,20.18,90.3,27.53,14.273,2,-0.017,250,0
72,73,Thu Feb 18 11:45:19 2021,36,1,364032,4063,312960,13988,32696,3329,...,34.6,1568,20.18,90.3,27.33,14.273,2,-0.017,250,1

In [3]:
path = "Data/validation"
val = pd.DataFrame()
os.listdir(path)
for i in os.listdir(path):
    if i.endswith('.csv'):
        df1 = pd.read_csv(path + "/"+ i)
        val = pd.concat([val,df1])
val

,ID,Tune Date,System,Test ID,69 m/z,70 m/z,219 m/z,220 m/z,502 m/z,503 m/z,...,Emission,EM Volts,Ent Lens,Ion Focus,Repeller,Ent Lens offset,Filament,Width219,Temp,Condition
0,1,Mon May 31 18:51:54 2021,19,2,335488,3872,436800,19576,39472,4181,...,35.0,1812,12.00,67.4,18.40,15.310,1,-0.011,230,0
1,2,Tue Jun 01 09:11:50 2021,19,2,401152,4621,534400,23064,47256,4663,...,35.0,1859,12.00,70.2,17.73,16.310,1,-0.010,230,0
2,3,Wed Jun 02 13:06:49 2021,19,2,299008,3565,460928,20112,54344,5414,...,35.0,1718,14.50,70.2,18.73,15.060,1,-0.008,230,0
3,4,Fri Jun 04 14:04:06 2021,19,2,298496,3332,430400,18936,53944,5389,...,35.0,1812,16.50,75.0,19.23,15.060,1,-0.010,230,0
4,5,Tue Jun 08 11:56:33 2021,19,2,309248,3621,401408,18520,52232,5294,...,35.0,1812,12.00,80.7,19.74,17.320,1,-0.015,230,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,80,Mon Jun 15 14:19:40 2020,36,1,487104,5374,507584,21432,58024,5526,...,34.6,1568,22.67,90.3,28.52,12.032,2,-0.019,250,0
80,81,Tue Jun 16 13:36:28 2020,36,1,351232,4015,358144,14609,38776,4284,...,34.6,1521,22.67,90.3,28.13,12.032,2,-0.017,250,0
81,82,Wed Jun 17 12:05:33 2020,36,1,340544,3444,343488,16313,38920,3576,...,34.6,1521,22.67,90.3,27.93,12.032,2,-0.019,250,0
82,83,Thu Jun 18 09:40:52 2020,36,1,447808,4965,433344,19664,49248,4555,...,34.6,1568,22.67,90.3,27.93,12.032,2,-0.019,250,0
83,84,Fri Jun 19 11:26:00 2020,36,1,346432,3502,337408,14924,37808,3437,...,34.6,1521,22.67,90.3,26.73,12.032,2,-0.019,250,1

In [4]:
df = df.drop(['ID', 'Test ID', 'System', 'Tune Date'], axis=1)
val = val.drop(['ID', 'Test ID', 'System', 'Tune Date'], axis=1)

In [6]:
# apply onehot encoding on Filament
df = pd.get_dummies(df, columns=['Filament'])
val = pd.get_dummies(val, columns=['Filament'])

In [8]:
X_train = df.drop(['Condition'], axis=1)
y_train = df['Condition']
X_val = val.drop(['Condition'], axis=1)
y_val = val['Condition']

In [9]:
# apply standard scalar
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_val = scaler.transform(X_val)

In [11]:
# apply over sampling
from imblearn.over_sampling import SMOTE
from collections import Counter

sm = SMOTE(random_state=42)
print('Original dataset shape %s' % Counter(y_train))
X_train, y_train = sm.fit_resample(X_train, y_train)
print('Resampled dataset shape %s' % Counter(y_train))

Original dataset shape Counter({0: 507, 1: 18})
Resampled dataset shape Counter({0: 507, 1: 507})

In [13]:
# random forest
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

rf = RandomForestClassifier()
rf.fit(X_train, y_train)
y_pred = rf.predict(X_val)
print("Accuracy:", accuracy_score(y_val, y_pred))
print("precision_score:", precision_score(y_val, y_pred))
print("recall_score:", recall_score(y_val, y_pred))
print("f1_score:", f1_score(y_val, y_pred))

Accuracy: 0.9497206703910615
precision_score: 0.0
recall_score: 0.0
f1_score: 0.0

In [14]:
# svc
from sklearn.svm import SVC
svc = SVC()
svc.fit(X_train, y_train)
y_pred = svc.predict(X_val)
print("Accuracy:", accuracy_score(y_val, y_pred))
print("precision_score:", precision_score(y_val, y_pred))
print("recall_score:", recall_score(y_val, y_pred))
print("f1_score:", f1_score(y_val, y_pred))

Accuracy: 0.9385474860335196
precision_score: 0.0
recall_score: 0.0
f1_score: 0.0